//////////////////////////////////////////////////////////////////////
// FILE: Main.cpp
//////////////////////////////////////////////////////////////////////

#ifndef NOMINMAX
#define NOMINMAX
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include "Core/CrashRecovery.h"
#include "Core/DebugLog.h"
#include "Core/LogService.h"
#include "Core/OptimizationCache.h"
#include "Core/PlatformGuard.h"
#include "Core/ProjectInfo.h"
#include "Tests/RunAll.h"
#include "UI/MainComponent.h"
// JUCE: only what this file uses (DocumentWindow, Desktop, String, ImageFileFormat, AlertWindow, FloatVectorOperations).
// Other modules (audio_devices, opengl, osc, etc.) are pulled in by MainComponent and downstream.
#include <juce_audio_basics/juce_audio_basics.h>
#include <juce_core/juce_core.h>
#include <juce_graphics/juce_graphics.h>
#include <juce_gui_basics/juce_gui_basics.h>
#include <memory>
#include <stdexcept>

// BinaryData: JuceLibraryCode/BinaryData.h (Projucer) or generated by PatchworldAssets (CMake)
#include "BinaryData.h"

using namespace juce;

// 1. DEFINE MainWindow FIRST so the Application class knows what it is
class MainWindow : public DocumentWindow {
public:
  MainWindow(String name)
      : DocumentWindow(
            name,
            Desktop::getInstance().getDefaultLookAndFeel().findColour(
                ResizableWindow::backgroundColourId),
            DocumentWindow::allButtons) {

    setUsingNativeTitleBar(true);

    // Initialize MainComponent safely
    DebugLog::debugLog("MainWindow: creating MainComponent...");
    auto *mainComp = new MainComponent();
    DebugLog::debugLog("MainWindow: MainComponent created");
    setContentOwned(mainComp, true);

#if JUCE_MAC || JUCE_WINDOWS || JUCE_LINUX
    // Safe Icon Loading (all desktop platforms)
    if constexpr (BinaryData::logo_pngSize > 0) {
      try {
        auto icon = ImageFileFormat::loadFrom(BinaryData::logo_png,
                                              BinaryData::logo_pngSize);
        if (icon.isValid())
          setIcon(icon);
      } catch (...) {
        LogService::instance().warning("Icon load failed (non-fatal)");
      }
    }
#endif

    setResizable(true, true);
    centreWithSize(860, 620);  // Compact default for small screens
    setVisible(true);

    LogService::instance().info("MainWindow initialized and visible.");
  }

  void closeButtonPressed() override {
    DebugLog::debugLog("closeButtonPressed: saving state...");
    if (auto *mainComp = dynamic_cast<MainComponent *>(getContentComponent()))
      mainComp->saveStateBeforeShutdown();
    DebugLog::debugLog("closeButtonPressed: requesting quit");
    JUCEApplication::getInstance()->systemRequestedQuit();
  }

private:
  JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MainWindow)
};

// 2. DEFINE Application Class SECOND
class StandaloneOSCApplication : public JUCEApplication {
public:
  StandaloneOSCApplication() {}

  // FIX: Add 'const' to match base class signature using ProjectInfo
  const String getApplicationName() override {
    return ProjectInfo::projectName;
  }
  const String getApplicationVersion() override {
    return ProjectInfo::versionString;
  }
  bool moreThanOneInstanceAllowed() override { return true; }

  void initialise(const String & /*commandLine*/) override {
    DebugLog::debugLog("initialise() started");
    LogService::instance().info("--- APP START ---");

    if (getCommandLineParameterArray().contains("--run-tests")) {
      bool ok = RunAllTests::run();
      setApplicationReturnValue(ok ? 0 : 1);
      systemRequestedQuit();
      return;
    }

    try {
      DebugLog::debugLog("FloatVectorOperations + MidiMath done");
      FloatVectorOperations::disableDenormalisedNumberSupport();
      MidiMath::initialize();

      // 2. Initialize Main Window
      DebugLog::debugLog("creating MainWindow...");
      mainWindow.reset(new MainWindow(getApplicationName()));
      DebugLog::debugLog("MainWindow created OK");

    } catch (const std::exception &e) {
      DebugLog::debugLog(String("CRASH std::exception: ") + e.what());
      juce::String userMsg = "The application could not start. ";
      if (e.what() && e.what()[0] != '\0')
        userMsg += "Details: " + String(e.what());
      else
        userMsg += "Please try again or restart your computer.";
      LogService::instance().error("CRASH (Std): " + String(e.what()));
      AlertWindow::showMessageBoxAsync(AlertWindow::WarningIcon,
                                       "Startup Error", userMsg);
      quit();
    } catch (...) {
      DebugLog::debugLog("CRASH unknown exception (MainWindow creation)");
      LogService::instance().error("CRASH (Unknown exception during MainWindow creation)");
      AlertWindow::showMessageBoxAsync(AlertWindow::WarningIcon,
                                       "Startup Error",
                                       "The application encountered an unexpected error while starting. Please try again or restart your computer.");
      quit();
    }
  }

  void shutdown() override {
    DebugLog::debugLog("shutdown() started");
    LogService::instance().info("--- APP SHUTDOWN ---");
    CrashRecovery::clearRecoveryPoint();
    DebugLog::debugLog("shutdown: destroying MainWindow (MainComponent dtor will run)...");
    mainWindow = nullptr;
    DebugLog::debugLog("shutdown() done");
  }

  void systemRequestedQuit() override { quit(); }

  void anotherInstanceStarted(const String & /*commandLine*/) override {}

private:
  std::unique_ptr<MainWindow> mainWindow;
};

START_JUCE_APPLICATION(StandaloneOSCApplication)